// SPDX-License-Identifier: Apache-2.0
import type { Catalog, FieldSpec } from "../catalog/model";

/**
 * The catalog as runtime data, shared by the browser SDK (debug tooling) and
 * the JVM (the event registry in Phase 2). Both copies are byte-identical.
 *
 * Key order is fixed and every map is sorted, so the output is stable across
 * machines and a diff shows only real catalog changes.
 */
export function runtimeCatalogJson(catalog: Catalog): string {
  const doc = {
    $comment: "GENERATED by `omnirec generate` from catalog/. Do not edit by hand.",
    catalogVersion: catalog.catalogVersion,
    schemaVersion: catalog.schemaVersion,
    domains: catalog.domains.map((d) => ({ id: d.id, title: d.title })),
    vocabularies: Object.fromEntries(catalog.vocabularies.map((v) => [v.name, v.values.map((x) => x.value)])),
    blocks: Object.fromEntries(
      catalog.blocks.map((b) => [
        b.name,
        Object.fromEntries(Object.entries(b.fields).sort(([a], [c]) => a.localeCompare(c)).map(([k, f]) => [k, fieldJson(f)])),
      ])
    ),
    events: catalog.events.map((e) => ({
      name: e.name,
      domain: e.domain,
      version: e.version,
      kind: e.kind,
      control: e.control,
      sources: e.sources,
      blocks: e.blocks,
      aliases: e.aliases,
      autocapture: e.autocapture,
      required: e.required,
      // Only fields the event itself declares or refines. Unrefined block
      // fields are already described under "blocks".
      fields: Object.fromEntries(
        e.fields.filter((f) => f.refined).map((f) => [f.path, fieldJson(f)])
      ),
    })),
  };
  return JSON.stringify(doc, null, 2) + "\n";
}

function fieldJson(field: FieldSpec): Record<string, unknown> {
  const out: Record<string, unknown> = { type: field.type };
  if (field.required) out.required = true;
  if (field.vocabulary) out.vocabulary = field.vocabulary;
  if (field.minimum !== undefined) out.minimum = field.minimum;
  if (field.maximum !== undefined) out.maximum = field.maximum;
  if (field.minItems !== undefined) out.minItems = field.minItems;
  if (field.maxLength !== undefined) out.maxLength = field.maxLength;
  if (field.pattern !== undefined) out.pattern = field.pattern;
  if (field.items) out.items = fieldJson(field.items);
  if (field.fields) {
    out.fields = Object.fromEntries(
      Object.entries(field.fields)
        .sort(([a], [b]) => a.localeCompare(b))
        .map(([k, f]) => [k, fieldJson(f)])
    );
  }
  return out;
}
