// SPDX-License-Identifier: Apache-2.0

/** One file a generator wants to exist, with its full content. */
export interface GeneratedFile {
  /** Repository-relative path with forward slashes. */
  path: string;
  content: string;
}

/**
 * Where generated output lives. Every file inside an owned directory must be
 * produced by the generator: anything else there is stale and is removed on
 * `generate` or reported by `generate --check`.
 */
export interface OutputLayout {
  ownedDirectories: string[];
}

export const GENERATED_NOTICE = "GENERATED by `omnirec generate` from catalog/. Do not edit by hand.";

export const PATHS = {
  tsDir: "packages/commerce-web/src/events/generated",
  tsCatalog: "packages/commerce-web/src/events/generated/catalog.ts",
  tsCatalogJson: "packages/commerce-web/src/events/generated/catalog.json",
  javaDir: "backend/omnirec-commerce-core/src/main/java/io/omnirec/commerce/catalog/generated",
  javaStandardEvents:
    "backend/omnirec-commerce-core/src/main/java/io/omnirec/commerce/catalog/generated/StandardEvents.java",
  javaResourceDir: "backend/omnirec-commerce-core/src/main/resources/omnirec",
  javaCatalogJson: "backend/omnirec-commerce-core/src/main/resources/omnirec/catalog.json",
  schemaTemplate: "catalog/envelope/v1.schema.json",
  schema: "schema/commerce-event.schema.json",
  docsDir: "docs/events",
} as const;

export const OWNED: OutputLayout = {
  ownedDirectories: [PATHS.tsDir, PATHS.javaDir, PATHS.javaResourceDir, PATHS.docsDir],
};
