# SPDX-License-Identifier: Apache-2.0
server:
  port: 8080

omnirec:
  web:
    cors:
      allowed-origins:
        - http://localhost:3000

  recommendation:
    aws-personalize:
      enabled: ${PERSONALIZE_ENABLED:false}
      access-key: ${AWS_ACCESS_KEY:}
      secret-key: ${AWS_SECRET_KEY:}
      region: ${AWS_REGION:us-east-1}
      campaign-arn: ${PERSONALIZE_CAMPAIGN_ARN:}
      tracking-id: ${PERSONALIZE_TRACKING_ID:}
    google-rec-ai:
      enabled: ${GOOGLE_RECAI_ENABLED:false}
      project-number: ${GOOGLE_PROJECT_NUMBER:}
      catalog-id: default_catalog
      event-store-id: default_event_store
      serving-config-id: ${GOOGLE_SERVING_CONFIG_ID:}
      credentials-file: ${GOOGLE_APPLICATION_CREDENTIALS:}

  cache:
    redis:
      enabled: ${REDIS_ENABLED:false}
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

logging:
  level:
    io.omnirec: INFO
