// SPDX-License-Identifier: Apache-2.0
import type { Plan } from "./plan";
import { STANDARD, type RuntimeCatalog, type RuntimeEvent, type RuntimeField } from "./runtime";

const NOTICE = "GENERATED by `omnirec generate` from omnirec.plan.yaml. Do not edit by hand.";

/**
 * `omnirec.d.ts`: teaches `track()` in @omnirec/commerce-web (and the
 * framework packages, which re-export it) the plan's custom events, by
 * augmenting `OmnirecCustomEvents`.
 */
export function pluginTypes(plan: Plan, catalog: RuntimeCatalog = STANDARD): string {
  const vocabularies = { ...catalog.vocabularies, ...plan.vocabularies };
  const lines = [`// ${NOTICE}`, `import "@omnirec/commerce-web";`, "", `declare module "@omnirec/commerce-web" {`];
  lines.push("  interface OmnirecCustomEvents {");
  for (const event of plan.events) {
    if (event.description) lines.push(`    /** ${event.description.replace(/\*\//g, "*\\/")} */`);
    const type = dataType(event, catalog, vocabularies);
    lines.push(`    ${event.name}: ${type};`);
    for (const alias of event.aliases) lines.push(`    ${alias}: OmnirecCustomEvents[${JSON.stringify(event.name)}];`);
  }
  lines.push("  }", "}", "", "export {};", "");
  return lines.join("\n");
}

function dataType(event: RuntimeEvent, catalog: RuntimeCatalog, vocabularies: Record<string, string[]>): string {
  const members: string[] = [];
  for (const block of event.blocks) {
    const fields: Record<string, RuntimeField> = { ...(catalog.blocks[block] ?? {}) };
    let blockRequired = false;
    for (const [path, field] of Object.entries(event.fields)) {
      if (!path.startsWith(`${block}.`)) continue;
      const name = path.slice(block.length + 1);
      fields[name] = { ...fields[name], ...field };
      if (field.required) blockRequired = true;
    }
    const body = Object.entries(fields)
      .map(([name, field]) => `${name}${field.required ? "" : "?"}: ${tsType(field, vocabularies)}`)
      .join("; ");
    members.push(`${block}${blockRequired ? "" : "?"}: { ${body} }`);
  }
  for (const [path, field] of Object.entries(event.fields)) {
    if (path.includes(".")) continue;
    members.push(`${path}${field.required ? "" : "?"}: ${tsType(field, vocabularies)}`);
  }
  return members.length ? `{ ${members.join("; ")} }` : "Record<string, never>";
}

export function tsType(field: RuntimeField, vocabularies: Record<string, string[]>): string {
  switch (field.type) {
    case "string":
    case "timestamp":
      return "string";
    case "integer":
    case "number":
      return "number";
    case "money":
      return "number | string";
    case "boolean":
      return "boolean";
    case "enum": {
      const values = vocabularies[field.vocabulary ?? ""] ?? [];
      return values.length ? values.map((v) => JSON.stringify(v)).join(" | ") : "string";
    }
    case "array":
      return field.items ? `Array<${tsType(field.items, vocabularies)}>` : "unknown[]";
    case "object": {
      const entries = Object.entries(field.fields ?? {});
      if (!entries.length) return "Record<string, unknown>";
      return `{ ${entries.map(([n, f]) => `${n}${f.required ? "" : "?"}: ${tsType(f, vocabularies)}`).join("; ")} }`;
    }
  }
}

/** `OmnirecEvents.java`: a constant per custom event, for `OmnirecTracker` and `@TrackEvent`. */
export function javaConstants(plan: Plan, javaPackage: string): string {
  const lines = [`// ${NOTICE}`, `package ${javaPackage};`, "", "/** Custom events from the tracking plan. */"];
  lines.push("public final class OmnirecEvents {", "");
  for (const event of plan.events) {
    if (event.description) lines.push(`    /** ${event.description.replace(/\*\//g, "*\\/")} */`);
    lines.push(`    public static final String ${event.name.toUpperCase()} = ${JSON.stringify(event.name)};`, "");
  }
  lines.push("    private OmnirecEvents() {", "    }", "}", "");
  return lines.join("\n");
}
